name: Bug report
description: Create a report to help us improve

body:
- type: markdown
  attributes:
    value: |
      Your issue may already have been reported!  Please search the existing issues before opening a new one.

- type: textarea
  id: outline
  attributes:
    label: Brief outline of the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  id: mwe
  attributes:
    label: Minimal working example (MWE)
    description: |
      Every bug report MUST INCLUDE a MWE. If you think your bug report does not need a MWE, please outline below why.
    placeholder: |
      ```latex
      \documentclass{article}
      % Any preamble code goes here
      \begin{document}
      % Demonstration of issue here
      \end{document}
      ```
  validations:
    required: true
