blank_issues_enabled: true
contact_links:
  - name: PGF/TikZ mailing list
    url: https://tug.org/mailman/listinfo/pgf-tikz
    about: You can also ask and answer questions on the mailing list
  - name: PGF/TikZ Matrix room
    url: https://matrix.to/#/#pgf-tikz:matrix.org
    about: The Matrix chat is ideal for informal and open-ended discussions
