name: Feature request
description: Suggest an idea for this project
labels:
- Feature Request

body:
- type: textarea
  id: description
  attributes:
    label: Brief outline of the proposed feature
    description: A clear and concise description of what you have in mind.
  validations:
    required: true

- type: textarea
  id: example
  attributes:
    label: Usage example
    description: Please showcase the semantics you want for the proposed feature, if applicable.
    placeholder: |
      ```latex
      \documentclass{article}
      % Any preamble code goes here
      \begin{document}
      % Demonstration of feature here
      \end{document}
      ```
