name: Documentation
description: Point out typos and other errors in the manual
labels:
- manual

body:
- type: markdown
  attributes:
    value: |
      Please only report issues against the latest version of the manual:
      https://pgf-tikz.github.io/pgf/pgfmanual.pdf

- type: input
  id: version
  attributes:
    label: Version
    description: Please insert the version from the title page

- type: textarea
  id: details
  attributes:
    label: Details
    description: |
      Please state what is wrong and on which page. If you want to report something as simple as a typo, please consider fixing it yourself and opening a Pull Request.
